name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: create a ZIP file
        run: zip -r sukkiri-c3-codes.zip chap*/* LICENSE.txt README.md &&
          unzip -t sukkiri-c3-codes.zip
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref_name }}
          files: sukkiri-c3-codes.zip
          draft: false
          prerelease: false
